'use client';
import { useMemo, useState } from 'react'; import GeneratorInput from '@/components/GeneratorInput'; import PhotoUploader from '@/components/PhotoUploader'; import LoadingGeneration from '@/components/LoadingGeneration'; import GeneratedPreview from '@/components/GeneratedPreview'; import { parsePrompt } from '@/lib/generator'; import { buildHtml } from '@/lib/exportHtml';
const steps=['Analyse du commerce','Détection du secteur','Création de la structure UX','Génération du copywriting','Intégration des photos','Création du formulaire','Optimisation mobile','Préparation de l’export'];
export default function Generator(){const [prompt,setPrompt]=useState('');const [images,setImages]=useState<string[]>([]);const [loading,setLoading]=useState(false);const [progress,setProgress]=useState(0);const [idx,setIdx]=useState(0);const [html,setHtml]=useState('');const [credits,setCredits]=useState(12); const [form,setForm]=useState({sector:'',style:'premium',goal:'devis'});
const step=useMemo(()=>steps[Math.min(idx,steps.length-1)], [idx]);
const generate=()=>{setLoading(true);setProgress(0);setIdx(0);const t=setInterval(()=>{setProgress(p=>{const np=p+13;setIdx(i=>Math.min(7,i+1));if(np>=100){clearInterval(t);const site=parsePrompt({prompt,sector:form.sector,style:form.style,objective:form.goal});const out=buildHtml(site,images);setHtml(out);setLoading(false);setCredits(c=>Math.max(0,c-1));return 100;}return np;});},850)};
const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'text/html'}));a.download='sitepilot-export.html';a.click();};
return <div className='space-y-6'>
<div className='glass rounded-2xl p-5 flex flex-wrap gap-3 items-center justify-between'><h1 className='text-3xl font-bold'>Générateur IA</h1><span className='badge'>Crédits restants: {credits}</span></div>
<GeneratorInput value={prompt} onChange={setPrompt}/>
<div className='grid md:grid-cols-3 gap-3 glass p-4 rounded-2xl'><select value={form.sector} onChange={e=>setForm({...form,sector:e.target.value})} className='bg-white/5 p-2 rounded'><option value=''>Secteur auto</option><option>beauté</option><option>restaurant</option><option>immobilier</option></select><select value={form.style} onChange={e=>setForm({...form,style:e.target.value})} className='bg-white/5 p-2 rounded'><option>premium</option><option>luxe</option><option>minimaliste</option><option>sombre</option></select><select value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})} className='bg-white/5 p-2 rounded'><option>devis</option><option>réservation</option><option>whatsapp</option><option>vente en ligne</option></select></div>
<PhotoUploader images={images} setImages={setImages}/>
<button disabled={loading||!prompt} onClick={generate} className='gradient-btn disabled:opacity-50'>{loading?'Génération...':'Générer le site'}</button>
{loading&&<LoadingGeneration progress={progress} step={step}/>} {html && <div className='space-y-3'><p className='text-emerald-400'>✅ Site prêt</p><div className='flex gap-2 flex-wrap'><button onClick={()=>navigator.clipboard.writeText(html)} className='px-3 py-2 rounded bg-white/10'>Copier HTML</button><button onClick={download} className='px-3 py-2 rounded bg-white/10'>Télécharger HTML</button><button onClick={generate} className='px-3 py-2 rounded bg-white/10'>Régénérer</button><button className='px-3 py-2 rounded bg-white/10'>Sauvegarder dans mes sites</button></div><GeneratedPreview html={html}/></div>}
</div>}
